---
title: "Using NLDI to find sites"
author: "Jordan S Read"
date: "June 2, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### load packages
```{r, warning=FALSE, message=FALSE}
library(powstreams)
library(dplyr)
library(dataRetrieval)

```

### get data
```{r, message=FALSE}
NLDI.url <- 'http://cida-test.er.usgs.gov/nldi/wqp/%s/navigate/UM/wqp?distance=1'
site <- 'nwis_12101100' %>% mda.streams::parse_site_name() %>% paste0('USGS-',.)

upstream.sites <- httr::GET(sprintf(NLDI.url, site)) %>% httr::content(as = 'text') %>% jsonlite::fromJSON()
print(upstream.sites)
```


### find your original site
```{r}
site.index <- upstream.sites$features$properties$identifier == site
site.comID <- upstream.sites$features$properties$comid[site.index]
## NHD comID:
print(site.comID)
## Lon, Lat values:
print(upstream.sites$features$geometry$coordinates[[which(site.index)]])
```

### find data from upstream sites
```{r}
siteids <- upstream.sites$features$properties$identifier[!site.index]

nutrient.data = readWQPdata(siteid=siteids, characteristicType="Nutrient")
nutrient.data %>% select(ActivityStartDate, CharacteristicName, ResultMeasureValue, ResultMeasure.MeasureUnitCode, MonitoringLocationIdentifier) %>% print
nutrient.data %>% group_by(MonitoringLocationIdentifier, CharacteristicName) %>% tally %>% arrange(desc(n))
```