meddle-version: "0.0.4"
document-created: "20171110"
document-creator: "Alison P Appling"

# ----data release----
title: Model configurations for estimating metabolism

# ----dataset details----
process-description: >-
  Metabolism was estimated using the streamMetabolizer package (Appling et al. 2018) using the Bayesian model with streamMetabolizer model name "b_Kb_oipi_tr_plrckm.stan".
  This configuration file was generated 2017-04-06 15:04:23 +0000 and was originally labeled with tag 1.0.2.
process-date: 2017-04-06 15:04:23 +0000
data-name: config.zip
data-description: Model configurations for estimating metabolism. Configuration parameters can be 
build-environment: stuff on mac things on pc, R versions etc
file-format: tab-separated values, compressed from text to .zip format
metadata-date: "`r format(Sys.time(),'%Y%m%d')"

# ----spatial data----
indirect-spatial: U.S.A.
latitude-res: Not applicable
longitude-res: Not applicable

# ----processing citations----
source-cites: 
  -
    authors: ['Alison P. Appling', 'Robert O. Hall Jr.', 'Charles B. Yackulic', 'Maite Arroita']
    title: >-
      Overcoming Equifinality: Leveraging Long Time Series for Stream Metabolism Estimation
    pubdate: 2018
    link: https://dx.doi.org/10.1002/2017JG004140
    sngdate:
      caldate: 2018
    srccurr: publication date
    srccitea: Appling et al. 2018
    srccontr: >-
      This methods manuscript justifies the metabolism model implementation used to generate metabolism estimates
      for this project.
  -
    authors: ['Alison P. Appling', 'Robert O. Hall Jr.', 'Maite Arroita', 'Charles B. Yackulic']
    title: >-
      streamMetabolizer: Models for Estimating Aquatic Photosynthesis and Respiration, version 0.10.1
    pubdate: 2017
    link: ['https://github.com/USGS-R/streamMetabolizer/releases/tag/v0.10.1', 'zenodo.org/record/838795#.Waw5zFWGOUk']
    sngdate:
      caldate: 2017
    srccurr: access date
    srccitea: Appling et al. 2017
    srccontr: >-
      This software source provided the metabolism model implementation used to generate metabolism estimates
      for this project. See https://dx.doi.org/10.5281/zenodo.838795 for an archived copy of the source code
      exactly as used for this project. See https://owi.usgs.gov/R/gran.html for instructions on how to access
      current versions of the software from the U.S. Geological Survey archive.
