times: ['2006-10-01', '2016-06-01']
nldas_url: 'dods://cida-eros-netcdfdev.er.usgs.gov:8080/thredds/dodsC/thredds_workspace/stream_metab/nldas.ncml'
gldas_url: 'dods://cida-eros-netcdfdev.er.usgs.gov:8080/thredds/dodsC/thredds_workspace/stream_metab/gldas.ncml'
version: rds
posted_after: '2016-07-12'
temp_dir: ../1_timeseries/cache
on_exists: skip
archive_existing: TRUE
day_hours: [4, 28]
