---
title: "Stream Metabolism Gap Analysis"
author: "Lindsay Carr, Alison Appling, Jordan Read"
date: "November 18, 2015"
---
  
```{r}
library(mda.streams)
library(dplyr)
library(unitted)
```

##State Discharge & DO 

The following state maps depict the geographic locations for dissolved oxygen (DO) and discharge sites. The states shown below are New Hampshire, Puerto Rico, North Carolina, Florida, Wisconsin, Arizona, and Connecticut.   

```{r, echo=FALSE, warning=FALSE, message=FALSE, eval=TRUE}
library(leaflet)
library(dataRetrieval)
library(DT)

disch.code = unique(get_var_src_codes(var=="disch", out='p_code'))
doobs.code = "00300"
min.count = 100
skip.types = c('GW','LK','ES')

get_site <- function(stateCd, pCd){
  filter(readNWISdata(service = "site", stateCd=stateCd,seriesCatalogOutput="true",outputDataTypeCd="iv",parameterCd=pCd,Access="3"), parm_cd==pCd) %>% 
    filter(count_nu > min.count) %>% 
    filter(!(site_tp_cd %in% skip.types)) %>% 
    filter(!is.na(dec_long_va))
}

make_map <- function(state){
  state.cd = stateCd$STUSAB[stateCd$STATE_NAME == state]
  
  
  clean_site <- function(site){
    clean.site= select(site, site_no, station_nm, dec_lat_va, dec_long_va, loc_web_ds, begin_date, end_date, count_nu) %>%
      rename(days_recorded = count_nu, device=loc_web_ds, latitude=dec_lat_va, longitude=dec_long_va) %>% 
      mutate(name=gsub("\\b([a-z])([a-z]+)", "\\U\\1\\L\\2" ,tolower(station_nm), perl=TRUE)) %>% 
      mutate(site_no = paste0('nwis_',site_no)) %>% 
      select(-station_nm)
    return(clean.site)
  }
  
  do.sites = get_site(state.cd, doobs.code) %>% 
    clean_site()
  disch.sites = get_site(state.cd, disch.code) %>% 
    clean_site()
  
  m = leaflet() %>% 
    addProviderTiles("CartoDB.Positron",
                     options = leaflet::providerTileOptions(noWrap = TRUE)) %>% 
    addCircleMarkers(lng = do.sites$longitude, 
                     lat = do.sites$latitude, 
                     popup = do.sites$station_nm, color = '#ff0000') %>% 
    addCircleMarkers(lng = disch.sites$longitude, 
                     lat = disch.sites$latitude, 
                     popup = disch.sites$station_nm, color = 'blue', radius = 3) %>% 
    addLegend("bottomright", labels = c('DO', 'Discharge'), 
              colors = c('red', 'blue'), title = 'Metabolism Site Types')
  
  return(list(map=m, disch=disch.sites, do = do.sites))
}
```

####New Hampshire
```{r}
#, echo=FALSE, warning=FALSE, message=FALSE, eval=TRUE
mapper = make_map('New Hampshire')
mapper$map
```
DO stations
```{r}
datatable(mapper$do, rownames = FALSE)
```
Discharge stations
```{r}
datatable(mapper$disch, rownames = FALSE)
```
