---
title: "MLE methods for smoothing K600 estimates"
author: "Alison Appling"
date: "November 24, 2015"
output: html_document
---

```{r, message=FALSE}
library(mda.streams)
library(streamMetabolizer)
library(dplyr)
```

# One model at a time

Generate a preliminary estimate of K600. This could be done with `metab_night`, `metab_mle`, or any other model that estimates K600.
```{r}
site <- "nwis_08062500"

# pull the data from ScienceBase
data_choices <- c(solar.time="sitetime_calcLon", DO.obs="doobs_nwis", DO.sat="dosat_calcGGbts", 
                  depth="depth_calcDischHarvey", temp.water="wtr_nwis", light="par_calcLat")
ts_merged <- get_ts(data_choices, site_name=site, method="approx", approx_tol=as.difftime(3, units="hours"))
data <- ts_merged %>% setNames(c("DateTime", names(data_choices))) %>% select(-DateTime) %>% unitted::v() %>%
  filter(solar.time > as.POSIXct("2013-01-01") & solar.time < as.POSIXct("2015-01-01"))

# fit a first-round MLE and extract the K estimates
mm1 <- metab_mle(data=data)
K600_mm1 <- predict_metab(mm1) %>% select(local.date, K600, K600.lower, K600.upper)

# smooth the K600s
tdata_choices <- c(solar.time="sitetime_calcLon", discharge='veloc_calcDischHarvey')
kts_merged <- get_ts(tdata_choices, site_name=site, method="approx", approx_tol=as.difftime(3, units="hours"))
kdata  <- kts_merged %>% setNames(c("DateTime", names(tdata_choices))) %>% select(-DateTime) %>% unitted::v() %>%
  filter(solar.time > as.POSIXct("2013-01-01") & solar.time < as.POSIXct("2015-01-01"))
mm2 <- metab_Kmodel(data=kdata, data_daily=K600_mm1, method='lm', weights = "CI", 
                    predictors=c("discharge.daily"), transforms=c(K600='log',discharge='log'))
K600_mm2 <- predict_metab(mm2) %>% select(local.date, K600)

# refit the MLE with fixed K
mm3 <- metab_mle(data=data, data_daily=K600_mm2)
met_mm3 <- predict_metab(mm3)
```

```{r, fig.width=9, fig.height=6}
# compare the two MLE results
plot_metab_preds(predict_metab(mm1))
```

```{r, fig.width=9, fig.height=6}
plot_metab_preds(predict_metab(mm3))
```


# Using config files
```{r}
message("stay tuned")
# config_one <- stage_metab_config(
#   tag='0.0.0', strategy='demo K600 smoothing', 
#   model='metab_mle', model_args='list(start_date="2014-03-15", end_date="2015-03-15")')
```