run1:
  tag: 1.0.0
  posted_after: 2017-02-01
  runid: ['170212A', '170211A', '170210C', '170210B', '170210A'] # first ID in list will get used to create next set of cluster files

run2:
  tag: 1.0.1
  posted_after: 2017-02-01
  runid: ['170302', '170224', '170221', '170219', '170218', '170217', '170214A', '170213A', '170212B'] # first ID in list will get used to create next set of cluster files

run3:
  tag: 1.0.2
  posted_after: 2017-04-01
  runid: ['170405'] # first ID in list will get used to create next set of cluster files
